/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import registros.RegistroTienda;
import paneles.*;
/**
 *
 * @author grifiun
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    //instanaciamos los paneles
    private PanelCargaDatos panelCD;
    private PanelLogin panelLogin;
    //creamos el jscrollpane
    JScrollPane contenedorPanel;
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        
            initComponents();
            initContenedorPaneles();
            
            
            if(verificarExistenciaRegistro()){//si hay datos cargamos el login
                panelLogin = new PanelLogin();
                cargarPanel(panelLogin);
            }else{//si no hay datos mostramos el panel de cargar datos
                panelCD = new PanelCargaDatos();            
                cargarPanel(panelCD);
            }            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    /**
     * Se cargan los paneles;
     */
    private void initContenedorPaneles() {        
        contenedorPanel = new JScrollPane();   
        contenedorPanel.setBounds(2, 2, 713, 413);//Agregamos posicion y tamano
        add(contenedorPanel);
    }
    
    /**
     * Se carga el panel mandado
     * @param JPanel 
     */
    private void cargarPanel(JPanel panelAux) {
        contenedorPanel.setViewportView(panelAux);//cargamos el panel
    }
    
    /**
     * Funcion  encargada de revisar la existencia de datos
     * @return 
     */
    private boolean verificarExistenciaRegistro() {            
        try {
            //Instanciamos 
            boolean existenciaRegistro;
            RegistroTienda rt = new RegistroTienda();
            //Verificamos la existencia de archivos
            return existenciaRegistro = rt.verificarExistenciaRegisgtroTienda(conection_data_base.EnlaceJDBC.EnlaceJDBC());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }        
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
