/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import entidades.Compra;
import funciones.ComboBoxCargarDato;
import funciones.SubStringDatos;
import graficos.MenuPrincipal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import registros.RegistroCompra;
import registros.RegistroDatos;
import registros.RegistroPedido;

/**
 *
 * @author grifiun
 */
public class PanelFacturarPedido extends javax.swing.JPanel {
    
    String codigoCompra;
    String anticipo;
    /**
     * Creates new form PanelFacturarPedido
     */
    public PanelFacturarPedido() {
        initComponents();
        cargarPedidos();
        generarCodigos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCreditoAUsar = new javax.swing.JFormattedTextField();
        txtCancelar = new javax.swing.JButton();
        btnRegistrarCompra = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtCodTienda = new javax.swing.JTextField();
        txtNitCliente = new javax.swing.JTextField();
        boxCodPedido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblPrecioPorPagar = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setText("FACTURAR PEDIDO");

        jLabel3.setText("*Cod. Tienda:");

        jLabel7.setText("Total: Q.");

        lblPrecio.setText("0.00");

        jLabel11.setText("*Credito a usar:");

        txtCreditoAUsar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter((DecimalFormat)NumberFormat.getNumberInstance(Locale.US))));

        txtCancelar.setText("Cancelar");
        txtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelarActionPerformed(evt);
            }
        });

        btnRegistrarCompra.setText("Registrar");
        btnRegistrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCompraActionPerformed(evt);
            }
        });

        jLabel5.setText("*NIT Cliente:");

        txtCodTienda.setEnabled(false);

        txtNitCliente.setEnabled(false);

        jLabel2.setText("Cod. Pedido:");

        jButton1.setText("Cargar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("*Estado:");

        txtEstado.setEnabled(false);

        jLabel4.setText("Por pagar: Q");

        lblPrecioPorPagar.setText("0.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(295, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(333, 333, 333))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(boxCodPedido, 0, 307, Short.MAX_VALUE)
                                    .addComponent(txtCodTienda)
                                    .addComponent(txtCreditoAUsar)
                                    .addComponent(txtNitCliente)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(138, 138, 138)
                                .addComponent(jLabel4)
                                .addGap(96, 96, 96))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRegistrarCompra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(118, 118, 118)
                                        .addComponent(lblPrecioPorPagar))
                                    .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(275, 275, 275))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxCodPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCreditoAUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNitCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblPrecioPorPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarCompra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCancelar)
                .addContainerGap(134, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelarActionPerformed
        PanelEmpleado panelEmpleado = new PanelEmpleado();
        MenuPrincipal.cargarPanel(panelEmpleado);
    }//GEN-LAST:event_txtCancelarActionPerformed

    private void generarCodigos(){   
        RegistroCompra rc = new RegistroCompra();
        codigoCompra = String.valueOf(rc.generarCodAleatorio());
    }
    
    private void btnRegistrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCompraActionPerformed
        conection_data_base.Consulta.mensajesEmergentes = false;
        try{
            RegistroDatos rd = new RegistroDatos();
            String[] creditoActualCliente = rd.obtenerDatos("Cliente", "credito", " WHERE nit = '"+txtNitCliente.getText()+"'");
            if(Double.parseDouble(txtCreditoAUsar.getText()) > Double.parseDouble(creditoActualCliente[0])){//Revisamos si el credito actual del cliente lo cubre
                JOptionPane.showMessageDialog(null, "El credito que quiere usar es mayor al credito actual: "+creditoActualCliente[0]);
            }else{                
                try{//Se verifica si el pedido se registro                    
                    registrarCompra();
                    JOptionPane.showMessageDialog(this, "REGISTRO HECHO CON EXITO");
                    PanelPedidos panel = new PanelPedidos();
                    MenuPrincipal.cargarPanel(panel);      
                    
                    if(txtEstado.getText().equals("RETRASADO")){
                        String creditoExtra = "";
                        if(anticipo.equalsIgnoreCase(lblPrecio.getText())){
                            creditoExtra = String.valueOf((Double.parseDouble(lblPrecio.getText()))*(5)/(100));//recibe el 5%
                        }else{
                            creditoExtra = String.valueOf((Double.parseDouble(lblPrecio.getText()))*(2)/(100));//recibe el 2%
                        }                        
                        JOptionPane.showMessageDialog(null, "Su pedido fue entregado con retraso, recibira \n"
                                + "un extra de credito de Q"+creditoExtra);
                        ArrayList<String> datos = new ArrayList();//removemos los datos del arraylist
                        datos.add(String.valueOf((Double.parseDouble(creditoActualCliente[0])) + (Double.parseDouble(creditoExtra))));//actualizamos el credito
                        datos.add(txtNitCliente.getText());

                        rd.actualizarDatos(datos, "Cliente", "credito ", "nit");                        
                    }
                    
                    ArrayList<String> datos = new ArrayList();
                        datos.add("ENTREGADO");//agregamos el nuevo estado
                        datos.add(String.valueOf(boxCodPedido.getSelectedItem()));//Agregamos el valor del codigo del pedido
                        rd.actualizarDatos(datos, "Pedido", "estado", "codigo_pedido");    
                    
                }catch(Exception ex){
                    System.out.println("Se produjo un error al verificar el exito del registro");
                }

            }

        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Error al realizar el registro");
        }

        conection_data_base.Consulta.mensajesEmergentes = true;
    }//GEN-LAST:event_btnRegistrarCompraActionPerformed

    private void registrarCompra(){
        Compra entidadAux = new Compra(codigoCompra, txtCreditoAUsar.getText(), lblPrecio.getText(), txtCodTienda.getText()
        ,txtNitCliente.getText(), String.valueOf(boxCodPedido.getSelectedItem()));
        
        SubStringDatos auxiliarSubDatos = new SubStringDatos("Compra (");
        auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_compra(), "codigo_compra");
        auxiliarSubDatos.agregarSubStringYDato(entidadAux.getEfectivo(), ", efectivo");
        auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCredito_usado(), ", credito_usado");
        auxiliarSubDatos.agregarSubStringYDato(entidadAux.getPrecio_total(), ", precio_total");
        auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_tienda(), ", codigo_tienda");
        auxiliarSubDatos.agregarSubStringYDato(entidadAux.getNit_cliente(), ", nit_cliente");
        auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_pedido(), ", codigo_pedido");

        //REGISTRAMOS EL CLIENTE
        RegistroDatos regAux = new RegistroCompra(auxiliarSubDatos.getSubOrden());//Le agregamos la suborden
        regAux.registrarDatos(auxiliarSubDatos.getDatos());//creamos el registro con los datos
        
        RegistroDatos rd = new RegistroDatos();
        String[] creditoActualCliente = rd.obtenerDatos("Cliente", "credito", " WHERE nit = '"+txtNitCliente.getText()+"'");

        ArrayList<String> datos = new ArrayList();//removemos los datos del arraylist
        datos.add(String.valueOf(Double.parseDouble(creditoActualCliente[0]) - Double.parseDouble(entidadAux.getCredito_usado())));//actualizamos el credito
        datos.add(txtNitCliente.getText());

        rd.actualizarDatos(datos, "Cliente", "credito ", "nit");
        
    };
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        RegistroDatos rd = new RegistroDatos();
        ArrayList<String> datos = new ArrayList();
        datos.add(String.valueOf(boxCodPedido.getSelectedItem()));
        String[][] aux = rd.obtenerDatos("SELECT codigo_tienda_2, estado, nit_cliente, anticipo FROM Pedido WHERE codigo_pedido = ?", datos);
        try{
            txtCodTienda.setText(aux[0][0]);
            txtEstado.setText(aux[0][1]);
            txtNitCliente.setText(aux[0][2]);
            
            String[][] aux2 = rd.obtenerDatos("SELECT codigo_pedido, SUM(subtotal) total FROM Subpedido WHERE codigo_pedido = ? GROUP BY codigo_pedido", datos);
            lblPrecio.setText(aux2[0][1]);
            anticipo = aux[0][3];
            lblPrecioPorPagar.setText(String.valueOf(Double.parseDouble(aux2[0][1])- Double.parseDouble(aux[0][3])) );
        }catch(Exception ex){
        
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Cargamos los productos de la tienda de origen
     */
    private void cargarPedidos(){
        boxCodPedido.removeAllItems();
        ComboBoxCargarDato cargarDato = new ComboBoxCargarDato();
        JComboBox cboxAux = new JComboBox();
        cboxAux = cargarDato.cargar("codigo_pedido", "Pedido", "estado", "RECIBIDO","estado","RETRASADO");//mandamos le nombre del atributo y nombre de la tabla
        //Pasamos el contenido de un cbo auxiliar al que nos interesa
        for (int i = 0; i < cboxAux.getItemCount(); i++) 
        {
            boxCodPedido.addItem(String.valueOf(cboxAux.getItemAt(i)));
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCodPedido;
    private javax.swing.JButton btnRegistrarCompra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPrecioPorPagar;
    private javax.swing.JButton txtCancelar;
    private javax.swing.JTextField txtCodTienda;
    private javax.swing.JFormattedTextField txtCreditoAUsar;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNitCliente;
    // End of variables declaration//GEN-END:variables
}
