/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import conection_data_base.Consulta;
import entidades.Empleado;
import funciones.SubStringDatos;
import graficos.MenuPrincipal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import registros.RegistroDatos;
import registros.RegistroEmpleado;

/**
 *
 * @author grifiun
 */
public class PanelCreacionEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PanelCreacionEmpleado
     */
    public PanelCreacionEmpleado() {
        initComponents();
        cargarTiendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarTienda = new javax.swing.JButton();
        txtNIT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTelefonoEmpleado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCancelar = new javax.swing.JButton();
        txtCodigoEmpleado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblTituloNuevaTienda = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDPI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTienda = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        btnRegistrarTienda.setText("Registrar");
        btnRegistrarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTiendaActionPerformed(evt);
            }
        });

        txtNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNITActionPerformed(evt);
            }
        });

        jLabel6.setText("NIT:");

        txtTelefonoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoEmpleadoActionPerformed(evt);
            }
        });

        jLabel7.setText("*Telefono:");

        txtCancelar.setText("Cancelar");
        txtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("*Cod empleado");

        lblTituloNuevaTienda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTituloNuevaTienda.setText("INGRESO NUEVO EMPLEADO");

        jLabel2.setText("*Nombre:");

        txtDPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDPIActionPerformed(evt);
            }
        });

        jLabel3.setText("*DPI:");

        txtCorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEmpleadoActionPerformed(evt);
            }
        });

        jLabel4.setText("*Correo:");

        txtDireccionEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEmpleadoActionPerformed(evt);
            }
        });

        jLabel5.setText("*Direccion:");

        jLabel9.setText("Tienda:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTituloNuevaTienda)
                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNIT, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDPI, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCorreoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTituloNuevaTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCancelar)
                    .addComponent(btnRegistrarTienda))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTiendaActionPerformed
        
        Empleado entidadAux = new Empleado(txtCodigoEmpleado.getText(), txtNombreEmpleado.getText(), txtDPI.getText(), txtCorreoEmpleado.getText(),
                txtDireccionEmpleado.getText(), txtNIT.getText(), txtTelefonoEmpleado.getText(), String.valueOf(txtTienda.getSelectedItem()));
        //Revisamos los campos obligatorios, si están llenos o vacíos
        if(entidadAux.getCodigo_empleado().isEmpty() || entidadAux.getNombre_empleado().isEmpty() || entidadAux.getDpi().isEmpty()
                || entidadAux.getCorreo_empleado().isEmpty() || entidadAux.getDirreccion_empleado().isEmpty() || entidadAux.getTelefono_empleado().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos obligatorios (*)");
        }else{
            //instanciamos y agregamos todos los datos
            SubStringDatos auxiliarSubDatos = new SubStringDatos("Empleado (");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_empleado(), "codigo_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getNombre_empleado(), ", nombre_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getDpi(), ", dpi");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCorreo_empleado(), ", correo_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getDirreccion_empleado(), ", direccion_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getNit_empleado(), ", nit_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getTelefono_empleado(), ", telefono_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_tienda(), ", codigo_tienda");
            

            //REGISTRAMOS EL EMPLEADO
            RegistroDatos regEmpleado = new RegistroEmpleado(auxiliarSubDatos.getSubOrden());//Le agregamos la suborden
            regEmpleado.registrarDatos(auxiliarSubDatos.getDatos());//creamos el registro con los datos
            
        }
        
    }//GEN-LAST:event_btnRegistrarTiendaActionPerformed

    private void txtNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNITActionPerformed

    private void txtTelefonoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoEmpleadoActionPerformed

    private void txtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelarActionPerformed
        PanelEmpleado panelEmpleado = new PanelEmpleado();
        MenuPrincipal.cargarPanel(panelEmpleado);
    }//GEN-LAST:event_txtCancelarActionPerformed

    private void txtDPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDPIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDPIActionPerformed

    private void txtCorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEmpleadoActionPerformed

    private void txtDireccionEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEmpleadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTienda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTituloNuevaTienda;
    private javax.swing.JButton txtCancelar;
    private javax.swing.JTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtCorreoEmpleado;
    private javax.swing.JTextField txtDPI;
    private javax.swing.JTextField txtDireccionEmpleado;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtTelefonoEmpleado;
    private javax.swing.JComboBox<String> txtTienda;
    // End of variables declaration//GEN-END:variables

    /**
     * Agregamos al comboBox las tiendas existentes
     */
    private void cargarTiendas() {
        
        try(ResultSet rs = Consulta.consultaOrden("SELECT codigo_tienda FROM Tienda")){
            //Agregamos los codigos de las tiendas al comboBox
            while(rs.next()){
                txtTienda.addItem(rs.getString("codigo_tienda"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(PanelCreacionEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
