/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import entidades.Empleado;
import funciones.SubStringDatos;
import graficos.MenuPrincipal;
import javax.swing.JOptionPane;
import registros.RegistroDatos;
import registros.RegistroEmpleado;
import funciones.ComboBoxCargarDato;
import javax.swing.JComboBox;
/**
 *
 * @author grifiun
 */
public class PanelCreacionEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form PanelCreacionEmpleado
     */
    public PanelCreacionEmpleado() {
        initComponents();
        cargarTiendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarTienda = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblTituloNuevaTienda = new javax.swing.JLabel();
        txtNombreEmpleado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCorreoEmpleado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDireccionEmpleado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTienda = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCodigoEmpleado = new javax.swing.JFormattedTextField();
        txtDPI = new javax.swing.JFormattedTextField();
        txtNIT = new javax.swing.JFormattedTextField();
        txtTelefonoEmpleado = new javax.swing.JFormattedTextField();

        btnRegistrarTienda.setText("Registrar");
        btnRegistrarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTiendaActionPerformed(evt);
            }
        });

        jLabel6.setText("NIT:");

        jLabel7.setText("*Telefono:");

        txtCancelar.setText("Cancelar");
        txtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("*Cod empleado");

        lblTituloNuevaTienda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTituloNuevaTienda.setText("INGRESO NUEVO EMPLEADO");

        jLabel2.setText("*Nombre:");

        jLabel3.setText("*DPI:");

        txtCorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEmpleadoActionPerformed(evt);
            }
        });

        jLabel4.setText("*Correo:");

        txtDireccionEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEmpleadoActionPerformed(evt);
            }
        });

        jLabel5.setText("*Direccion:");

        txtTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTiendaActionPerformed(evt);
            }
        });

        jLabel9.setText("Tienda:");

        txtCodigoEmpleado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtDPI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtNIT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtTelefonoEmpleado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoEmpleado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrarTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombreEmpleado)
                    .addComponent(txtCorreoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtDPI, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNIT)
                    .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblTituloNuevaTienda)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(276, 276, 276))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblTituloNuevaTienda)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCancelar)
                    .addComponent(btnRegistrarTienda))
                .addContainerGap(111, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTiendaActionPerformed
        
        Empleado entidadAux = new Empleado(txtCodigoEmpleado.getText(), txtNombreEmpleado.getText(), txtDPI.getText(), txtCorreoEmpleado.getText(),
                txtDireccionEmpleado.getText(), txtNIT.getText(), txtTelefonoEmpleado.getText(), String.valueOf(txtTienda.getSelectedItem()));
        //Revisamos los campos obligatorios, si están llenos o vacíos
        if(entidadAux.getCodigo_empleado().isEmpty() || entidadAux.getNombre_empleado().isEmpty() || entidadAux.getDpi().isEmpty()
                || entidadAux.getCorreo_empleado().isEmpty() || entidadAux.getDirreccion_empleado().isEmpty() || entidadAux.getTelefono_empleado().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos obligatorios (*)");
        }else{
            //instanciamos y agregamos todos los datos
            SubStringDatos auxiliarSubDatos = new SubStringDatos("Empleado (");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_empleado(), "codigo_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getNombre_empleado(), ", nombre_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getDpi(), ", dpi");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCorreo_empleado(), ", correo_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getDirreccion_empleado(), ", direccion_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getNit_empleado(), ", nit_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getTelefono_empleado(), ", telefono_empleado");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_tienda(), ", codigo_tienda");
            

            //REGISTRAMOS EL EMPLEADO
            RegistroDatos regEmpleado = new RegistroEmpleado(auxiliarSubDatos.getSubOrden());//Le agregamos la suborden
            regEmpleado.registrarDatos(auxiliarSubDatos.getDatos());//creamos el registro con los datos
            
        }
        
    }//GEN-LAST:event_btnRegistrarTiendaActionPerformed

    private void txtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelarActionPerformed
        PanelEmpleado panelEmpleado = new PanelEmpleado();
        MenuPrincipal.cargarPanel(panelEmpleado);
    }//GEN-LAST:event_txtCancelarActionPerformed

    private void txtCorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEmpleadoActionPerformed

    private void txtDireccionEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEmpleadoActionPerformed

    private void txtTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTiendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTienda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTituloNuevaTienda;
    private javax.swing.JButton txtCancelar;
    private javax.swing.JFormattedTextField txtCodigoEmpleado;
    private javax.swing.JTextField txtCorreoEmpleado;
    private javax.swing.JFormattedTextField txtDPI;
    private javax.swing.JTextField txtDireccionEmpleado;
    private javax.swing.JFormattedTextField txtNIT;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JFormattedTextField txtTelefonoEmpleado;
    private javax.swing.JComboBox<String> txtTienda;
    // End of variables declaration//GEN-END:variables

    /**
     * Agregamos al comboBox las tiendas existentes
     */
    private void cargarTiendas() {
        ComboBoxCargarDato cargarDato = new ComboBoxCargarDato();
        JComboBox cboxAux = new JComboBox();
        cboxAux = cargarDato.cargar("codigo_tienda", "Tienda");//mandamos le nombre del atributo y nombre de la tabla
        //Pasamos el contenido de un cbo auxiliar al que nos interesa
        for (int i = 0; i < cboxAux.getItemCount(); i++) 
        {
            txtTienda.addItem(String.valueOf(cboxAux.getItemAt(i)));
        }

    }
}
