/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import entidades.Tienda;
import funciones.SubStringDatos;
import graficos.MenuPrincipal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import registros.RegistroDatos;
import registros.RegistroTienda;

/**
 *
 * @author grifiun
 */
public class PanelCreacionTienda extends javax.swing.JPanel {

    /**
     * Creates new form PanelCreacionTienda
     */
    public PanelCreacionTienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloNuevaTienda = new javax.swing.JLabel();
        txtNombreTienda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDireccionTienda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegistrarTienda = new javax.swing.JButton();
        txtHorario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCancelar = new javax.swing.JButton();
        txtCodigoTienda = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JFormattedTextField();
        txtTelefono2 = new javax.swing.JFormattedTextField();

        lblTituloNuevaTienda.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTituloNuevaTienda.setText("INGRESO NUEVA TIENDA");

        jLabel2.setText("*Nombre:");

        txtDireccionTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionTiendaActionPerformed(evt);
            }
        });

        jLabel3.setText("*Direccion:");

        jLabel4.setText("*Telefono 1:");

        jLabel5.setText("Telefono 2:");

        btnRegistrarTienda.setText("Registrar");
        btnRegistrarTienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTiendaActionPerformed(evt);
            }
        });

        txtHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHorarioActionPerformed(evt);
            }
        });

        jLabel6.setText("Horario:");

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        jLabel7.setText("Correo:");

        txtCancelar.setText("Cancelar");
        txtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelarActionPerformed(evt);
            }
        });

        jLabel8.setText("*Cod tienda");

        txtTelefono1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtTelefono2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloNuevaTienda)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCodigoTienda)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRegistrarTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCorreo)
                            .addComponent(txtHorario)
                            .addComponent(txtDireccionTienda)
                            .addComponent(txtNombreTienda)
                            .addComponent(txtTelefono1)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(296, 296, 296))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(lblTituloNuevaTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCancelar)
                    .addComponent(btnRegistrarTienda))
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDireccionTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionTiendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionTiendaActionPerformed

    private void txtHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHorarioActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed
    /**
     * Regresamos a la pantalla anterior
     * @param evt 
     */
    private void txtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelarActionPerformed
       PanelIngresarRegistros panelEmpleado = new PanelIngresarRegistros();
        MenuPrincipal.cargarPanel(panelEmpleado);
    }//GEN-LAST:event_txtCancelarActionPerformed

    /**
     * Recibimos los parametros y registramos en la DB
     * Agregamos todos los datos que no sean vacíos
     * @param evt 
     */
    private void btnRegistrarTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTiendaActionPerformed
       Tienda entidadAux = new Tienda(txtCodigoTienda.getText(), txtNombreTienda.getText(), txtDireccionTienda.getText(), txtTelefono1.getText(), txtTelefono2.getText(), txtHorario.getText(), txtCorreo.getText());
       //Revisamos los campos obligatorios, si están llenos o vacíos      
       if(entidadAux.getCodigo_tienda().isEmpty() || entidadAux.getNombre_tienda().isEmpty() || entidadAux.getDireccion_tienda().isEmpty() || entidadAux.getTelefono_1().isEmpty()){
            JOptionPane.showMessageDialog(null, "Los primeros 4 datos son obligatorios");
       }else{
            //instanciamos y agregamos todos los datos
            SubStringDatos auxiliarSubDatos = new SubStringDatos("Tienda (");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCodigo_tienda(), "codigo_tienda");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getNombre_tienda(), ", nombre_tienda");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getDireccion_tienda(), ", direccion_tienda");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getTelefono_1(), ", telefono_1");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getTelefono_2(), ", telefono_2");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getHorario(), ", horario");
            auxiliarSubDatos.agregarSubStringYDato(entidadAux.getCorreo(), ", correo");
            

            //REGISTRAMOS LA TIENDA
            RegistroDatos regAux = new RegistroTienda(auxiliarSubDatos.getSubOrden());//Le agregamos la suborden
            regAux.registrarDatos(auxiliarSubDatos.getDatos());//creamos el registro con los datos
            
            PanelCreacionTiempoEnvio ct = new PanelCreacionTiempoEnvio(entidadAux.getCodigo_tienda());
            MenuPrincipal.cargarPanel(ct);
       }
    }//GEN-LAST:event_btnRegistrarTiendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarTienda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblTituloNuevaTienda;
    private javax.swing.JButton txtCancelar;
    private javax.swing.JTextField txtCodigoTienda;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccionTienda;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNombreTienda;
    private javax.swing.JFormattedTextField txtTelefono1;
    private javax.swing.JFormattedTextField txtTelefono2;
    // End of variables declaration//GEN-END:variables
}
