/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import graficos.MenuPrincipal;
import static graficos.MenuPrincipal.contenedorPanel;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import registros.RegistroDatos;

/**
 *
 * @author grifiun
 */
public class PanelEnlistarRegistro extends javax.swing.JPanel {
    private String[] nombreTablas = {"Tienda", "Empleado", "Cliente"};
    private String[][] nombreColumnas = { "Cod. Tienda,nombre,direccion,telefono,telefono 2,horario,correo".split(","),
        "Cod. Empleado,nombre,DPI,Correo,Direccion,NIT,Telefono,Trabaja en".split(","),
        "NIT,nombre,Telefono,Correo,Direccion,DPI,Credito".split(",")};
    
    private JPanel panelParaTabla;    
    
    /**
     * Creates new form PanelEnlistarRegistro
     */
    public PanelEnlistarRegistro() {
        initComponents();
        prepararPanelTabla();
                
        prepararTabla(nombreTablas[0], nombreColumnas[0]);
    }

    /**
     * Funcion que actualizara la tabla con la informacion
     * de la tabla elegida
     * @param nombreTabla 
     */
    public void prepararTabla(String nombreTabla, String[] tituloColumnas){        
        RegistroDatos regD = new RegistroDatos();
        JTable tablaAux;        
        tablaAux = new JTable(regD.obtenerDatos(nombreTabla), tituloColumnas);   
        tablaAux.setLayout(null);
        tablaAux.setBounds(0, 0, 680, 330);
        
        panelParaTabla.setLayout(new BorderLayout());
        panelParaTabla.add(tablaAux.getTableHeader(), BorderLayout.PAGE_START);
        panelParaTabla.add(tablaAux, BorderLayout.CENTER);        
    }
    
    public void prepararPanelTabla(){
        panelParaTabla = new JPanel();
        panelParaTabla.setLayout(null);
        panelParaTabla.setBounds(30, 38, 680, 330);
        this.add(panelParaTabla);       
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        comboBoxTabla = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("LISTADOS");

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        comboBoxTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tienda", "Empleado", "Cliente" }));
        comboBoxTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTablaActionPerformed(evt);
            }
        });

        btnRegresar.setText("regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar)
                    .addComponent(comboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        PanelEmpleado panelEmpleado = new PanelEmpleado();
        MenuPrincipal.cargarPanel(panelEmpleado);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
       panelParaTabla.removeAll();
       prepararTabla(nombreTablas[comboBoxTabla.getSelectedIndex()], nombreColumnas[comboBoxTabla.getSelectedIndex()]);
       panelParaTabla.updateUI();//refrescamos el panel
    }//GEN-LAST:event_btnCargarActionPerformed

    private void comboBoxTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTablaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> comboBoxTabla;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
